# Generated by Django 2.0.4 on 2018-04-24 06:25

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DAppAdiYazilar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yazilartabloadiklasi',
            name='yazar_modelden',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Yazilar', to=settings.AUTH_USER_MODEL, verbose_name='Yazar'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='yazilartabloadiklasi',
            name='metin',
            field=ckeditor.fields.RichTextField(verbose_name='İçerik'),
        ),
    ]
